name: Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:

    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v4
      - run: docker build . -t ankitadasgupta14/next-js-app
      - run: echo "${{secrets.DOCKERHUB_SECERET}}" | docker login -u ${{secrets.DOCKERHUBUSERNAME}} --password-stdin
      - run: docker push ankitadasgupta14/next-js-app:latest